trigger: none

parameters:
- name: client
  displayName: "Client name"
  type: string
  default: ""

- name: modules
  displayName: "Modules needed for this client (comma-separated)"
  type: string
  default: "security"

resources:
  repositories:
    - repository: terraform-modules
      type: github

      name: Kartavya0206/testing
      endpoint: github.com_Kartavya0206
      ref: refs/heads/main

stages:
- stage: Fetch_Modules
  displayName: Fetch Selected Terraform Modules
  jobs:
  - job: Fetch
    displayName: Copy Selected Modules
    pool:
      name: Windows-SelfHosted
      demands:
        - Agent.Name -equals testingvm

    steps:
    - checkout: self
      displayName: Checkout Self Repository
      fetchDepth: 1
      persistCredentials: true

    - checkout: terraform-modules
      displayName: Checkout Terraform Modules
      path: terraform-modules
      fetchDepth: 1

    - powershell: |
        $client = "${{ parameters.client }}".Trim()
        $modules = "${{ parameters.modules }}".Split(",") | ForEach-Object { $_.Trim() }
        if ($client) { Write-Host "Client: $client" }
        Write-Host "Modules needed for this client: $($modules -join ', ')"

        $workspace = "$(Pipeline.Workspace)"
        $selfRoot = "$workspace\s"

        # Find GitHub repo root: try resource name first, then any folder that isn't "s"
        $githubRoot = $null
        if (Test-Path "$workspace\terraform-modules") { $githubRoot = "$workspace\terraform-modules" }
        else {
          Get-ChildItem -Path $workspace -Directory | Where-Object { $_.Name -ne "s" } | ForEach-Object { if (-not $githubRoot) { $githubRoot = $_.FullName } }
        }
        if (-not $githubRoot -or -not (Test-Path $githubRoot)) {
          Write-Host "Workspace contents:"
          Get-ChildItem -Path $workspace -Directory | ForEach-Object { Write-Host "  - $($_.Name)" }
          Write-Error "GitHub repo checkout not found under $workspace. Expected folder 'terraform-modules' or repo name (e.g. 'testing')."
          exit 1
        }
        Write-Host "Using GitHub repo at: $githubRoot"

        $sourceRoot = if (Test-Path (Join-Path $githubRoot "modules")) { Join-Path $githubRoot "modules" } else { $githubRoot }
        $clientSlug = if ($client) { $client -replace '\s+', '-' } else { "default" }
        $destinationRoot = "$selfRoot\clients\$clientSlug\modules"

        if (-not (Test-Path $sourceRoot)) {
            Write-Error "Modules directory not found at $sourceRoot"
            exit 1
        }

        Write-Host "`n Available modules:"
        Get-ChildItem $sourceRoot -Directory | ForEach-Object { Write-Host "  - $($_.Name)" }

        New-Item -ItemType Directory -Force -Path $destinationRoot | Out-Null

        foreach ($module in $modules) {
          $module = $module.Trim()
          $sourcePath = Join-Path $sourceRoot $module
          $destinationPath = Join-Path $destinationRoot $module

          if (Test-Path $sourcePath) {
            Write-Host "Copying module: $module"
            Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse -Force
          } else {
            Write-Error "Module '$module' not found"
            exit 1
          }
        }

        Write-Host "`n Modules copied successfully"
      displayName: Copy Selected Modules

    - powershell: |
        # Push selected modules into this Azure DevOps repo (self)
        $repoRoot = "$(Pipeline.Workspace)\s"
        if (-not (Test-Path $repoRoot)) { Write-Error "Self repo not found at $repoRoot"; exit 1 }
        Set-Location $repoRoot

        git config user.email "pipeline@azuredevops.com"
        git config user.name "Azure Pipeline"
        git config core.askPass ""

        $clientSlug = ("${{ parameters.client }}".Trim() -replace '\s+', '-'); if (-not $clientSlug) { $clientSlug = "default" }
        $branchName = if ($clientSlug -ne "default") { "client-$clientSlug-modules-$(Build.BuildId)" } else { "modules-$(Build.BuildId)" }

        git checkout -b $branchName
        git add clients/

        Write-Host "Committing changes..."
        git commit -m "Client ${{ parameters.client }}: Fetched modules ${{ parameters.modules }} from GitHub"

        Write-Host "Pushing to Azure Repos..."
        git push -u origin $branchName

        if ($LASTEXITCODE -eq 0) {
            Write-Host "`n========================================" -ForegroundColor Green
            Write-Host " SUCCESS " -ForegroundColor Green
            Write-Host "========================================" -ForegroundColor Green
            Write-Host "`nModules for this client fetched from GitHub and pushed to Azure DevOps repo." -ForegroundColor Cyan
            Write-Host "`nBranch: $branchName" -ForegroundColor Yellow
            Write-Host "Path in repo: clients/$clientSlug/modules/" -ForegroundColor Yellow
            Write-Host "`n========================================" -ForegroundColor Green
        } else {
            Write-Error "Push failed"
            exit 1
        }
      displayName: Push to Azure Repos
      env:
        GIT_TERMINAL_PROMPT: 0